"""Stack: Manim CE. Render -qm, inspect, -qh, then -qk for the committed MP4.
Sources are local synthetic PCM WAVs generated by fourier-transform-lab.py.
"""
from pathlib import Path
import importlib.util
import numpy as np
from manim import *
ROOT=Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('lab',ROOT/'fourier-transform-lab.py');lab=importlib.util.module_from_spec(spec);spec.loader.exec_module(lab)
config.background_color='#1e1e1e'
TXT='#cccccc';DIM='#999999';BLUE='#60a5fa';PINK='#ed78b3';AMBER='#f4b44c';GREEN='#48bb96'
class FourierTransform(Scene):
 def words(self,s,y,size=28,color=TXT):
  m=Text(s,font_size=size,color=color).move_to([0,y,0])
  if m.width>13:m.scale_to_fit_width(13)
  return m
 def line(self,ax,x,y,color=BLUE,width=2):
  v=VMobject(color=color,stroke_width=width);v.set_points_as_corners([ax.c2p(float(a),float(b)) for a,b in zip(x,y)]);return v
 def envelope(self,ax,t,y,color=BLUE):
  # Display block extrema, not an undersampled oscillating polyline.
  blocks=[slice(a,min(a+80,len(y))) for a in range(0,len(y),80)]
  centers=np.array([np.mean(t[b]) for b in blocks]);lo=np.array([min(y[b]) for b in blocks]);hi=np.array([max(y[b]) for b in blocks])
  points=[ax.c2p(float(a),float(b)) for a,b in zip(centers,hi)]+[ax.c2p(float(a),float(b)) for a,b in zip(centers[::-1],lo[::-1])]
  return Polygon(*points,fill_color=color,fill_opacity=.75,stroke_color=color,stroke_width=.6)
 def caption(self,s):
  if hasattr(self,'cap') and self.cap in self.mobjects:self.play(FadeOut(self.cap),run_time=.3)
  self.cap=self.words(s,-3.35,25);self.play(FadeIn(self.cap),run_time=.35)
 def clear(self):self.play(*[FadeOut(m) for m in self.mobjects],run_time=.8)
 def construct(self):self.probes();self.window();self.echo()
 def probes(self):
  self.play(FadeIn(self.words('Find a frequency by cancelling the others',3.35,36)))
  eq=MathTex(r'x_n=e^{2\pi i3n/8},\quad X_k=\sum_{n=0}^7x_ne^{-2\pi ikn/8}',font_size=36,color=TXT).move_to([0,2.55,0]);self.play(FadeIn(eq));self.wait(3)
  ax=Axes(x_range=[-2,9,1],y_range=[-1,4,1],x_length=11,y_length=3.4,axis_config={'color':DIM,'include_tip':False}).move_to([0,-.3,0]);self.play(FadeIn(ax))
  real=Text('real contribution',font_size=22,color=DIM).move_to([4.7,-2.45,0]);imag=Text('imaginary',font_size=22,color=DIM).move_to([-5.4,1.7,0]);self.add(real,imag)
  for k in [2,3]:
   label=self.words(f'Probe bin k = {k}',1.8,29,AMBER);self.play(FadeIn(label));self.caption('Each arrow is one input sample multiplied by the rotating probe.')
   z=np.r_[0,np.cumsum(np.exp(2j*np.pi*(3-k)*np.arange(8)/8))];arrows=VGroup()
   for a,b in zip(z[:-1],z[1:]):
    ar=Arrow(ax.c2p(a.real,a.imag),ax.c2p(b.real,b.imag),buff=0,color=BLUE if k==2 else PINK,stroke_width=4,max_tip_length_to_length_ratio=.18);arrows.add(ar);self.play(FadeIn(ar),run_time=.35)
   dot=Dot(ax.c2p(z[-1].real,z[-1].imag),color=AMBER,radius=.07);self.play(FadeIn(dot))
   self.caption('Wrong frequency: the eight contributions sum to zero.' if k==2 else 'Matching frequency: all eight point along +1. The sum is 8.');self.wait(4)
   if k==2:self.play(FadeOut(arrows),FadeOut(dot),FadeOut(label),run_time=.6)
  self.wait(1);self.clear()
 def window(self):
  self.play(FadeIn(self.words('A changing sound needs a moving question',3.35,36)))
  t,x,freq=lab.demo_signal();M=1024;w=np.hanning(M);ff=np.fft.rfftfreq(M,1/lab.FS);mask=(ff>=100)&(ff<=600)
  ax=Axes(x_range=[0,4,1],y_range=[-.4,.4,.4],x_length=12,y_length=1.5,axis_config={'color':DIM,'include_tip':False}).move_to([0,1.3,0])
  bx=Axes(x_range=[100,600,100],y_range=[0,.36,.1],x_length=12,y_length=2,axis_config={'color':DIM,'include_tip':False}).move_to([0,-1.5,0])
  labels=VGroup(self.words('4-second min–max envelope  |  220 Hz → glide → 440 Hz',2.5,26),self.words('128 ms Hann window; amplitude-corrected local spectrum',.1,25),self.words('frequency / Hz',-2.9,21,DIM))
  labels.add(*[Text(str(f),font_size=19,color=DIM).move_to(bx.c2p(f,0)+DOWN*.2) for f in range(100,601,100)]);wave=self.envelope(ax,t,x,BLUE);self.play(FadeIn(ax),FadeIn(bx),FadeIn(wave),FadeIn(labels));self.wait(2)
  pos=ValueTracker(.2)
  def win():
   a=max(0,pos.get_value()-.064);b=min(4,pos.get_value()+.064)
   return Polygon(ax.c2p(a,-.4),ax.c2p(b,-.4),ax.c2p(b,.4),ax.c2p(a,.4),fill_color=AMBER,fill_opacity=.23,stroke_color=AMBER,stroke_width=2)
  def spectrum():
   start=int(round(pos.get_value()*lab.FS));segment=np.pad(x,(M//2,M//2))[start:start+M]
   spectrum=2*abs(np.fft.rfft(segment*w))/sum(w)
   return self.line(bx,ff[mask],spectrum[mask],PINK,4)
  moving=always_redraw(win);spec=always_redraw(spectrum);self.add(moving,spec)
  self.caption('Slow visual pass: the window selects only this neighbourhood in time.')
  self.play(pos.animate.set_value(3.8),run_time=12,rate_func=linear);self.wait(2)
  self.caption('Now listen at normal speed. Same signal, same analysis.');pos.set_value(0)
  self.add_sound(str(ROOT/'fourier-transform-changing-tone.wav'))
  self.play(pos.animate.set_value(4),run_time=4,rate_func=linear);self.wait(2)
  moving.clear_updaters();spec.clear_updaters();self.caption('A whole-recording magnitude plot does not directly show this sequence.');self.wait(4);self.clear()
 def echo(self):
  self.play(FadeIn(self.words('Convolution: every arrival is a delayed copy',3.35,36)))
  dry,h,wet=lab.echo_signal();T=len(wet)/lab.FS;t=np.arange(len(wet))/lab.FS;z=np.pad(dry,(0,len(wet)-len(dry)))
  ax=Axes(x_range=[0,4,1],y_range=[-.4,.4,.4],x_length=12,y_length=1.5,axis_config={'color':DIM,'include_tip':False}).move_to([0,1.5,0]);bx=ax.copy().move_to([0,-1.35,0])
  inputwave=self.envelope(ax,t,z,BLUE);outwave=self.envelope(bx,t,z,PINK)
  self.play(FadeIn(ax),FadeIn(bx),FadeIn(inputwave),FadeIn(outwave));self.play(FadeIn(self.words('Dry input — min–max envelope',2.6,27)),FadeIn(self.words('Output envelope: direct sound + reflections',-.25,27)))
  self.caption('A synthetic room response: direct, then 0.24, 0.48 and 0.72 seconds.')
  total=z.copy()
  for delay,gain in [(.24,.55),(.48,.30),(.72,.16)]:
   d=round(delay*lab.FS);copy=np.zeros(len(wet));copy[d:d+len(dry)]=gain*dry
   ghost=self.envelope(bx,t,copy,AMBER);self.play(FadeIn(ghost),run_time=.7);self.wait(1)
   total+=copy;self.play(Transform(outwave,self.envelope(bx,t,total,PINK)),FadeOut(ghost),run_time=1.2)
  self.caption('First: the dry plucks.');self.add_sound(str(ROOT/'fourier-transform-dry.wav'));self.wait(3.5)
  self.caption('Then: the convolution. Gain is unchanged; delayed copies are added.');self.add_sound(str(ROOT/'fourier-transform-echo.wav'));self.wait(4.3)
  self.caption('FFT multiplication wraps the tail unless both inputs are padded enough.');self.wait(4)
  self.clear();self.play(FadeIn(self.words('Change coordinates. Keep the information.',.8,38)),FadeIn(self.words('The FFT makes it fast. Windows and phase decide what you can recover.',-.35,25)));self.wait(5)
