"""Manim: asymmetric encryption as an open padlock, then as arithmetic on a clock.
Scene 1 — Alice publishes an open padlock (public key) and keeps the only key (private key);
          Bob snaps the padlock on his box; only Alice can open it.  Then the reverse: a wax seal
          only Alice can make (private key) that anyone can check against her public key (signature).
Scene 2 — the numbers: p=61, q=53, n=3233, e=17, d=2753; 65 → 65^17 mod 3233 = 2790 → 2790^2753 mod 3233 = 65.
Render: manim -qk encryption-padlock.py Padlock ; copy the MP4 to encryption-padlock.mp4 ; rm -rf media __pycache__"""
from manim import *
GREY = "#888888"; BLUE_K = "#2563eb"; GREEN_K = "#059669"; RED_K = "#dc2626"; AMBER = "#f59e0b"; PURPLE_K = "#7c3aed"

def padlock(color, open_=True):
    body = RoundedRectangle(width=0.7, height=0.55, corner_radius=0.08, fill_color=color, fill_opacity=0.9, stroke_width=0)
    sh = Arc(radius=0.22, start_angle=0, angle=PI, color=color, stroke_width=6).shift(UP*0.42)
    if open_: sh.shift(RIGHT*0.12 + UP*0.1)
    return VGroup(body, sh)

def key(color):
    return VGroup(Circle(radius=0.14, color=color, stroke_width=5), Line(ORIGIN, RIGHT*0.55, color=color, stroke_width=5).shift(RIGHT*0.14),
                  Line(RIGHT*0.5, RIGHT*0.5+DOWN*0.15, color=color, stroke_width=5), Line(RIGHT*0.65, RIGHT*0.65+DOWN*0.15, color=color, stroke_width=5))

class Padlock(Scene):
    def construct(self):
        self.camera.background_color = "#1e1e1e"
        title = Text("Asymmetric encryption: one lock, one key — and they are not the same object", font_size=30, color=GREY).to_edge(UP)
        self.add(title)
        alice = Text("Alice", font_size=30, color=GREY).move_to([-4.5, 2.2, 0]); bob = Text("Bob", font_size=30, color=GREY).move_to([4.5, 2.2, 0])
        self.add(alice, bob)
        # keypair generated by Alice
        pub = padlock(BLUE_K).move_to([-4.5, 0.8, 0]); priv = key(AMBER).move_to([-4.5, -0.6, 0])
        l1 = Text("public key = an open padlock", font_size=22, color=BLUE_K).next_to(pub, DOWN, buff=0.15)
        l2 = Text("private key = the only key that opens it", font_size=22, color=AMBER).next_to(priv, DOWN, buff=0.15)
        self.play(FadeIn(pub), FadeIn(l1)); self.play(FadeIn(priv), FadeIn(l2)); self.wait(0.8)
        # publish: many copies of the padlock go out
        copies = VGroup(*[padlock(BLUE_K).scale(0.6) for _ in range(4)])
        self.play(*[c.animate.move_to([x, 0.8, 0]) for c, x in zip(copies, [-1.5, 0.5, 2.5, 4.5])], run_time=1.6)
        pubnote = Text("published to everyone — copies cost nothing, the key never leaves Alice", font_size=22, color=GREY).move_to([0, -2.4, 0])
        self.play(FadeIn(pubnote)); self.wait(1)
        self.play(FadeOut(copies[:3]), FadeOut(pubnote))
        # Bob writes a message, puts it in a box, snaps the padlock
        box = Rectangle(width=1.3, height=0.9, color=GREY, stroke_width=3).move_to([4.5, -0.6, 0]); msg = Text("m", font_size=34, color=GREEN_K).move_to(box)
        self.play(FadeIn(box), FadeIn(msg))
        lock_on = padlock(BLUE_K, open_=False).scale(0.6).move_to([4.5, 0.1, 0])
        self.play(Transform(copies[3], lock_on)); ct = Text("c", font_size=34, color=RED_K).move_to(box)
        self.play(Transform(msg, ct)); n1 = Text("Bob encrypts with Alice's PUBLIC key — anyone can snap a padlock shut", font_size=22, color=GREY).move_to([0, -2.4, 0])
        self.play(FadeIn(n1)); self.wait(1)
        grp = VGroup(box, msg, copies[3]); self.play(FadeOut(l1), FadeOut(l2)); self.play(grp.animate.move_to([-1.4, -0.3, 0]), run_time=1.6)
        self.play(FadeOut(n1)); n2 = Text("only the PRIVATE key opens it — even Bob cannot reopen his own box", font_size=22, color=GREY).move_to([0, -2.4, 0])
        self.play(priv.animate.next_to(grp, LEFT, buff=0.2), FadeIn(n2)); self.play(FadeOut(copies[3]), Transform(msg, Text("m", font_size=34, color=GREEN_K).move_to(box))); self.wait(1.5)
        self.play(*[FadeOut(x) for x in [grp, n2, pub, priv]])
        # signature
        s1 = Text("Run backwards it is a signature", font_size=28, color=GREY).move_to([0, 1.4, 0]); self.play(FadeIn(s1))
        doc = Rectangle(width=1.6, height=1.0, color=GREY, stroke_width=3).move_to([-4.5, -0.2, 0]); dt = Text("doc", font_size=26, color=GREY).move_to(doc)
        seal = Circle(radius=0.22, color=AMBER, fill_color=AMBER, fill_opacity=0.9).move_to(doc.get_corner(DR) + [-0.3, 0.3, 0])
        priv2 = key(AMBER).move_to([-4.5, -1.6, 0])
        self.play(FadeIn(doc), FadeIn(dt), FadeIn(priv2)); self.play(FadeIn(seal)); n3 = Text("Alice seals with her PRIVATE key — nobody else can make this seal", font_size=22, color=GREY).move_to([0, -2.4, 0]); self.play(FadeIn(n3)); self.wait(0.8)
        g2 = VGroup(doc, dt, seal); self.play(g2.animate.move_to([4.5, -0.2, 0]), FadeOut(n3), run_time=1.4)
        pub2 = padlock(BLUE_K).scale(0.7).move_to([4.5, -1.6, 0]); tick = Text("✓", font_size=40, color=GREEN_K).next_to(seal, RIGHT, buff=0.15)
        n4 = Text("anyone checks the seal against Alice's PUBLIC key: authentic, and unaltered", font_size=22, color=GREY).move_to([0, -2.4, 0])
        self.play(FadeIn(pub2), FadeIn(n4)); self.play(FadeIn(tick)); self.wait(1.8)
        self.play(*[FadeOut(m) for m in self.mobjects if m is not title])
        # Scene 2: the arithmetic
        t2 = Text("What the padlock is made of: arithmetic on a clock with 3233 hours", font_size=28, color=GREY).move_to([0, 2.2, 0]); self.play(FadeIn(t2))
        setup = VGroup(Text("p = 61,  q = 53   (secret primes)", font_size=26, color=AMBER), Text("n = p × q = 3233   (public)", font_size=26, color=BLUE_K),
                       Text("φ = (p−1)(q−1) = 3120   (secret)", font_size=26, color=AMBER), Text("e = 17   (public)      d = 2753,  because 17 × 2753 = 1 + 15 × 3120", font_size=26, color=GREY)).arrange(DOWN, aligned_edge=LEFT, buff=0.22).move_to([0, 0.7, 0])
        self.play(Write(setup), run_time=3); self.wait(0.8)
        enc = Text("encrypt:   65¹⁷ mod 3233 = 2790", font_size=30, color=RED_K).move_to([0, -1.2, 0]); dec = Text("decrypt:   2790²⁷⁵³ mod 3233 = 65", font_size=30, color=GREEN_K).move_to([0, -1.8, 0])
        self.play(FadeIn(enc)); self.wait(0.6); self.play(FadeIn(dec)); self.wait(0.6)
        why = Text("it works because m^(e·d) = m^(1 + kφ) ≡ m  (mod n)  — Euler's theorem; and nobody can find d without φ, which needs p and q", font_size=20, color=GREY).move_to([0, -2.6, 0])
        self.play(FadeIn(why)); self.wait(2.5)
