"""A trace table, generated by running the code.

A trace table is a dry run written down: one column per variable, a new row
each time a value changes, an OUTPUT column.  This script produces one
automatically for any small function, by watching the function execute line
by line (sys.settrace) and recording every variable change -- so a hand-drawn
table can be checked against the machine's, which is the point of the card.

Run:  python3 pdlc-trace-table.py
"""
import sys

def trace_table(func, *args, watch=None):
    rows, last = [], {}
    outputs = []
    def tracer(frame, event, arg):
        if frame.f_code is not func.__code__:
            return tracer
        if event == "line" or event == "return":
            cur = {k: v for k, v in frame.f_locals.items() if not watch or k in watch}
            changed = {k: v for k, v in cur.items() if last.get(k, object()) != v}
            if changed or outputs:
                # Cambridge layout: keep filling the current row until a column would be overwritten
                if rows and not any(rows[-1].get(k, "") != "" for k in changed) and rows[-1]["OUTPUT"] == "":
                    row = rows[-1]
                else:
                    row = {k: "" for k in (watch or cur)}; row["OUTPUT"] = ""; rows.append(row)
                for k in changed: row[k] = cur[k]
                if outputs: row["OUTPUT"] = " / ".join(outputs); outputs.clear()
                last.update(cur)
        return tracer
    real_print = print
    def fake_print(*a, **k): outputs.append(" ".join(str(x) for x in a))
    func.__globals__["print"] = fake_print
    sys.settrace(tracer)
    try: func(*args)
    finally:
        sys.settrace(None); func.__globals__["print"] = real_print
    cols = (watch or list(rows[-1].keys())[:-1]) + ["OUTPUT"]
    w = {c: max(len(c), *(len(str(r.get(c, ""))) for r in rows)) for c in cols}
    real_print(" | ".join(c.ljust(w[c]) for c in cols))
    real_print("-+-".join("-" * w[c] for c in cols))
    for r in rows:
        if any(str(r.get(c, "")) != "" for c in cols):
            real_print(" | ".join(str(r.get(c, "")).ljust(w[c]) for c in cols))

# --- the March 2024 Paper 22 Q7 flowchart, as Python ---
def average_group_size(data):
    NumberGroups = 0
    Total = 0
    GroupSize = data.pop(0)
    while GroupSize != 0:
        NumberGroups = NumberGroups + 1
        Total = Total + GroupSize
        GroupSize = data.pop(0)
    Average = Total // NumberGroups          # DIV
    print("Average group size", Average)

print("0478 March 2024 Paper 22 Q7 -- input 7, 10, 2, 8, 3, 9, 0, 6\n")
trace_table(average_group_size, [7, 10, 2, 8, 3, 9, 0, 6], watch=["NumberGroups", "Total", "GroupSize", "Average"])
